//
//  ListOrdersWorkerTests.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 12/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanAppOldUI
import XCTest

class ListOrdersWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListOrdersWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListOrdersWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListOrdersWorker()
  {
    sut = ListOrdersWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testLoadProducts()
  {
    // Given
    
    // When
    sut.LoadProducts { products in
        XCTAssert(products.count == 2, "There should be 2 products")
    }
    
    // Then
  }
}
