//
//  ListOrdersInteractorTests.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 12/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanAppOldUI
import XCTest

class ListOrdersInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListOrdersInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListOrdersInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListOrdersInteractor()
  {
    sut = ListOrdersInteractor()
  }
  
  // MARK: Test doubles
  
  class ListOrdersPresentationLogicSpy: ListOrdersPresentationLogic
  {
    var presentProductsCalled = false
    
    func PresentProducts(response: ListOrders.LoadProducts.Response) {
        presentProductsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testListOrders()
  {
    // Given
    let spy = ListOrdersPresentationLogicSpy()
    sut.presenter = spy
    let request = ListOrders.LoadProducts.Request()
    
    // When
    sut.LoadProducts(request: request)
    
    // Then
    XCTAssertTrue(spy.presentProductsCalled, "presentProductsCalled(request:) should ask the presenter to format the result")
  }
}
