//
//  ProductDetailsPresenter.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 14/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresentationLogic
{
  func presentSomething(response: ProductDetails.Something.Response)
}

class ProductDetailsPresenter: ProductDetailsPresentationLogic
{
  weak var viewController: ProductDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProductDetails.Something.Response)
  {
    let viewModel = ProductDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
