//
//  ProductDetailsInteractor.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 14/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsBusinessLogic
{
    func doSomething(request: ProductDetails.Something.Request)
}

protocol ProductDetailsDataStore
{
    var product : Product {get set}
}

class ProductDetailsInteractor: ProductDetailsBusinessLogic, ProductDetailsDataStore
{
    var presenter: ProductDetailsPresentationLogic?
    var worker: ProductDetailsWorker?
    var product : Product = Product(name: "Not valid")
    
    // MARK: Do something
    
    func doSomething(request: ProductDetails.Something.Request)
    {
        worker = ProductDetailsWorker()
        worker?.doSomeWork()
        
        let response = ProductDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
