//
//  ListOrdersModels.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 10/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOrders
{
    // MARK: Use cases
    
    enum LoadProducts
    {
        struct Request
        {
            
        }
        
        struct Response
        {
            var products : [Product] = []
        }
        
        struct ViewModel
        {
            var products : [Product] = []
        }
    }
    
    enum DeleteProduct
    {
        struct Request
        {
            var productIndex : Int
        }
        
        struct Response
        {
            var productIndex : Int
        }
        
        struct ViewModel
        {
            var productIndex : Int
        }
    }
}
