//
//  ListOrdersRouter.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 10/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListOrdersRoutingLogic
{
    func RouteToProductDetails()
}

protocol ListOrdersDataPassing
{
    var dataStore: ListOrdersDataStore? { get set }
}

class ListOrdersRouter: NSObject, ListOrdersRoutingLogic, ListOrdersDataPassing
{
    weak var viewController: ListOrdersViewController?
    var dataStore: ListOrdersDataStore?
    
    // MARK: Routing
    
    func RouteToProductDetails()
    {
        let destinationVC = ProductDetailsViewController()
        var destinationDS = destinationVC.router?.dataStore
        
        PassDataToProductDetails(source: dataStore!, destination: &(destinationDS!))
        NavigateToProductDetails(source: viewController!, destination: destinationVC)
    }
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    func NavigateToProductDetails(source: ListOrdersViewController, destination: ProductDetailsViewController)
    {
        source.navigationController?.pushViewController(destination, animated: true)
        destination.ShowProductInfo()
    }
    
    // MARK: Passing data
    
    func PassDataToProductDetails(source: ListOrdersDataStore, destination: inout ProductDetailsDataStore)
    {
        destination.product = source.selectedProduct!
    }
}
