//
//  ListOrdersViewController.swift
//  CleanAppOldUI
//
//  Created by Ricardo Ruiz on 10/10/2019.
//  Copyright (c) 2019 Ricardo Ruiz. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersDisplayLogic: class
{
    func DisplayProducts(viewModel: ListOrders.LoadProducts.ViewModel)
    func DisplayNewProduct(viewModel: ListOrders.AddProduct.ViewModel)
    func DisplayDeletedProduct(viewModel: ListOrders.DeleteProduct.ViewModel)
}

class ListOrdersViewController: UITableViewController, ListOrdersDisplayLogic
{
    var interactor: ListOrdersBusinessLogic?
    var router: (NSObjectProtocol & ListOrdersRoutingLogic & ListOrdersDataPassing)?
    var productList : [Product] = []
    
    var addProductButton = UIButton()
    
    // MARK: Object lifecycle
    
    convenience init() {
        self.init(nibName: nil, bundle: nil)
    }
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ListOrdersInteractor()
        let presenter = ListOrdersPresenter()
        let router = ListOrdersRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        tableView.allowsMultipleSelectionDuringEditing = false
        
        addProductButton.setTitle("Add product", for: .normal)
        addProductButton.backgroundColor = .blue
        
        tableView.addSubview(addProductButton)
        addProductButton.translatesAutoresizingMaskIntoConstraints = false;
                
        addProductButton.leftAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.leftAnchor).isActive = true
        addProductButton.rightAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.rightAnchor).isActive = true
        addProductButton.bottomAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.bottomAnchor).isActive = true
        addProductButton.widthAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.widthAnchor).isActive = true
        addProductButton.heightAnchor.constraint(equalToConstant: 50).isActive = true
        
        addProductButton.addTarget(self, action: #selector(AddProduct), for: .touchUpInside)
        
        LoadProducts()
    }
    
    // MARK: Do something
    
    func LoadProducts()
    {
        let request = ListOrders.LoadProducts.Request()
        interactor?.LoadProducts(request: request)
    }
    
    @objc func AddProduct()
    {
        let request = ListOrders.AddProduct.Request()
        interactor?.AddProduct(request: request)
    }
    
    // MARK: Tableview delegates
    
    func DisplayProducts(viewModel: ListOrders.LoadProducts.ViewModel)
    {
        productList = viewModel.products
        
        tableView.reloadData()
    }
    
    func DisplayDeletedProduct(viewModel: ListOrders.DeleteProduct.ViewModel)
    {
        productList.remove(at: viewModel.productIndex)
        tableView.deleteRows(at: [IndexPath(row: viewModel.productIndex, section: 0)], with: .left)
    }
    
    func DisplayNewProduct(viewModel: ListOrders.AddProduct.ViewModel)
    {
        productList.append(viewModel.newProduct)
        tableView.insertRows(at: [IndexPath(row: productList.count - 1, section: 0)], with: .right)
    }

    // MARK: Delegate
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return productList.count
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = tableView.dequeueReusableCell(withIdentifier: "ProductCell")
        
        if cell == nil {
            cell = ProductTableViewCell(productName: productList[indexPath.row].name!)
        }
        
        return cell!
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        router?.dataStore?.selectedProduct = productList[indexPath.row]
        router?.RouteToProductDetails()
    }
    
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }
    
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if (editingStyle == UITableViewCell.EditingStyle.delete) {
            let deleteProductRequest = ListOrders.DeleteProduct.Request(productIndex: indexPath.row)
            interactor?.DeleteProduct(request: deleteProductRequest)
        }
    }
}
